Foteev KMP Dijkstra and lineral search add
maybe-hello-world/PY101-october pull request #28
Opened 2018-11-09 13:52 UTC by gitschon

2018-11-10 09:14 UTC, maybe-hello-world requested changes
Смотрите комментарии про линейный поиск.

2018-11-10 09:14 UTC, maybe-hello-world commented on Tasks/KMP.py
> +        result = np.zeros(len(prefix_str), dtype=int)
dtype лучше указывать из тех, которые заданы в numpy, так вы более точно контролируете.
np.int32, np.int8 и т.д.

2018-11-10 09:14 UTC, maybe-hello-world commented on Tasks/binary_search.py
> +    if elem < 0:
Сам элемент вполне может быть меньше нуля, у бинарного поиска проблем с этим не будет.
Главное, чтоб массив был отсортирован.

2018-11-10 09:14 UTC, maybe-hello-world commented on Tasks/binary_search.py
> +    if left_b > right_b or elem < 0:
аналогично вышесказанному

2018-11-10 09:14 UTC, maybe-hello-world commented on Tasks/linear_search.py
> +        my_cost = int(Graph.get_edge_data(*gr)['weight'])
Аналогично, вы ищете минимум, а затем вторым проходом ищете ребро, у которого этот минимум присутствует.
А я утверждаю, что это можно сделать за один проход, сразу сохраняя ребро, в котором нашелся минимум.
Реализуете? =)

2018-11-12 08:47 UTC, closed without merging

2018-11-12 08:52 UTC, gitschon commented on Tasks/linear_search.py
> +        my_cost = int(Graph.get_edge_data(*gr)['weight'])
Если правильно вас понял, то реализовал в новом коммите в модуле lineral_search_all_minimums.py